module.exports = {
  fontFamily: "'Helvetica', sans-serif",
  fontSize: 13,
  sliderHeight: 22,
  controlBgColor: '#444',
  fieldBgColor: '#333',
  fieldHoverColor: '#383838',
  fieldActiveColor: '#383838',
  fieldBorderColor: '#232323',
  fieldHeight: 30,
  sectionHeadingBgColor: '#222',
  sectionHeadingHoverColor: '#444',
  sectionHeadingColor: '#e8e8e8',
  sectionHeadingBorderColor: '#222',

  inactiveTabBgColor: '#333',
  inactiveTabColor: '#ccc',
  inactiveTabHoverBgColor: '#444',
  inactiveTabHoverColor: '#ccc',

  activeTabBgColor: '#555',
  activeTabColor: '#fff',

  controlBorderColor: '#666',
  sliderThumbColor: '#888',
  fontColor: '#e8e8e8',
  sectionHeadingHeight: 24,
  minLabelWidth: 110,
  minControlWidth: 130,
  visibilityFontColor: 'rgba(0, 0, 0, 0.3)',
  focusBorderColor: '#888',
  controlBorderRadius: 2,
};
